services:
  webhookservice.api:
    image: ${DOCKER_REGISTRY-}webhookserviceapi
    build:
      context: .
      dockerfile: WebhookService.API/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=WebhookDB;User Id=sa;Password=YourStrong@Password123;TrustServerCertificate=True
      - ConnectionStrings__Redis=redis:6379
      - Security__MasterKey=your-256-bit-base64-encoded-key-here
    depends_on:
      - sqlserver
      - redis
    networks:
      - webhook-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Password123
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - webhook-network

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - webhook-network

networks:
  webhook-network:
    driver: bridge

volumes:
  sqlserver-data: {}
  redis-data: {}

